### ISSUE TITLE
Calculate DE stats for rows with NA values

### ISSUE THREAD

**Issue by flevander** [ComputationalProteomics/NormalyzerDE#10]
Currently only rows without NA values are used for DE statistics, regardless of the leastRepCount setting if a batch variable is used. If possible, p-values should be calculated if the number of replicates with non-null values in each group to compare are at least those indicated by this setting, also for this setting. The functionality is there when no batch variable is given.

**Comment by Jakob37** [comment]
In discussion this was concluded to be a feature of Limma. If for a feature one condition is missing in all cases Limma with return a missing value for corresponding feature. Worth to note is also that if running with the batch correction option set all combination of levels of biological and batch factors need to have values, or a missing value will be returned.
