### ISSUE TITLE
rows with less that one non-NA in a group

### ISSUE THREAD

**Issue by Luq16** [ComputationalProteomics/NormalyzerDE#15]
I realised that rows with less that one non-NA in a group was filtered-out. Meanwhile, in my data I have 4 groups/conditions. It is possible that a protein is completely missing in a particular condition. What would you advice me to do? Is there a way to avoid this default filter?
Thank you in advance.

**Comment by Jakob37** [comment]
Hi @Luq16 , for the normalization part the full conditions is required for generating the performance measures. If you just are after the normalizations you could run with "skipAnalysis = TRUE". It might be that this currently also filters the low-abundance entries, but a workaround would be then to assign all the samples to one conditions (i.e. in the design matrix). Then you should get the normalized samples with no omitted entries.

Let me know if this helps, and if you have further questions.

I agree that it would be good to give the user more control here, I will consider whether that would be possible to implement.

**Comment by flevander** [comment]
If this concerns the statistics part you can run with leastRepCount = 0. This was previously not functioning properly, but is working from version 1.13.2.
