### ISSUE TITLE
How to perform local normalization?

### ISSUE THREAD

**Issue by Jeff-Gui** [ComputationalProteomics/NormalyzerDE#25]
Hi, I wonder if there is any option to perform local normalization within the replicate (RLR-R, VSN-R, LOESS-R). It seems that the output file of normalyzer() only contains global methods. Please correct me if my understanding is not correct. Thanks!

**Comment by Jakob37** [comment]
Hi Jeff! Sorry about the slow response, back from winter vacation now.

To use the local normalization, you need to have one column in your data containing the retention time (or other numerical values that you want to normalize locally over). Name this column 'RT'. Then NormalyzerDE should detect it automatically (and tell you so in the logs).

I.e. this type matrix would provide also local normalizations (the numbers are just example values):

```
RT   sample1 sample2 sample3 sample4
2      ... sample values
5      ... sample values
7      ... sample values
11    ... sample values
12    ... sample values
```

Just let me know if this does not solve the issue!

**Comment by Jakob37** [comment]
We realized that I didn't answer the correct question here. My response is on how to perform retention-time local normalization, not 'sample group local'. This is not included in NormalyzerDE. If you want to perform normalization within the replicate groups, you can use the previous 'Normalyzer': http://normalyzer.immunoprot.lth.se/

**Comment by Jakob37** [comment]
With that, I close this issue. Just let us know if this didn't address your question.
