### ISSUE TITLE
Output .txt datasets gene names formatted to dates

### ISSUE THREAD

**Issue by SauerTho** [ComputationalProteomics/NormalyzerDE#29]
First: thanks for the awesome package, got it up and running pretty quick and works like a charm - mostly.
I am using R and the normalyzerDE package on a MacOS machine.
I noticed a problem with the .txt outputs: some gene names (Mouse format) are automatically converted to a date format. Which makes it difficult for using those datasets downstream. This seems to occur during file  creation, as the misformatting is not only shown in Excel, but also in plain text editor on my Mac and the editor Atom.
Might the mac cause this problem? Can I change the output format to .csv? I could not find such an option in the package description.
Cheers
Thorben

**Comment by SauerTho** [comment]
Nevermind, the problem was in the input dataset...

**Comment by Jakob37** [comment]
Great to hear that you use NormalyzerDE, and that your issue was solved @L3ft2di3 !
