### ISSUE TITLE
Why plotting first sample in MA plot and first two samples in Scatter Plots

### ISSUE THREAD

**Issue by lisiarend** [ComputationalProteomics/NormalyzerDE#30]
Hey,

I just have a question concerning the MA plots, Scatter plots and QQ plots.

Is there a reasoning behind why only taking for example the first sample for the QQ-plots? Is there really no need to compare all samples or why do you only take the first sample?

And for the scatter plots for example, why do you only take the first two samples from each dataset to be plotted? Is that only a selection that you did or why the first two and no any two samples in the dataset?

And yes again the same question for the MA plots. Is it enough to only look at the MA plots of the first sample (first sample in each dataset plotted against average of replicate group that sample belong to)?

**Comment by Jakob37** [comment]
Hi!

Thanks for using NormalyzerDE.

You are right - plotting just the first pairs of samples is a shortcut here. It is just that it would be unpractical to plot all samples against each other in this kind of report.

If you are interested in more in-depth plotting of samples versus samples, then you would need to reach beyond NormalyzerDE.

We have a different software OmicLoupe which is designed to work well together with the output from NormalyzerDE. Here you could make MA plots and volcano plots for the different statistical comparisons you might be interested in:

http://quantitativeproteomics.org/omicloupe

For doing more comprehensive single-versus-single sample comparisons, the easiest is probably to load the data table into R and tidyverse.

You for instance could do something like the following to do pairwise sample scatterplot.

```
library(tidyverse)
my_table <- read_tsv("normalization_table.tsv")
ggplot(my_table, aes(x=first_sample_col, y=second_sample_col)) + geom_point()
```

Anyway, you make a good point, and it something that could be included as an "Advanced option" in the future.

Best of luck with the analysis!

**Comment by Jakob37** [comment]
I'll close this one now. Feel free to reopen if you want to continue the discussion.
