### ISSUE TITLE
analyzeNormalizations, the categoricalAnova parameter not used

### ISSUE THREAD

**Issue by IgnatiusPang** [ComputationalProteomics/NormalyzerDE#31]
Dear Mr. Willforss,

I'm currently using your NormalyzerDE package for my proteomics data analysis. I was doing the analyze normalization step but got error when running it. 

"Warning: not all values are positiveError in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
  NA/NaN/Inf in 'y'"

So I decided to turn off the 'categoricalAnova' variable and see if the analysis worked when I skip the ANOVA step, but changing the parameter seems to have no effect. Browsing through the code (see below) it seems to me that the categoricalAnova variable might not be carried out through the rest of the code (e.g. variable seems to be unused inside this function). Would you please have a look at this for me?

```
analyzeNormalizations <- function(nr, categoricalAnova=FALSE) {

    ner <- NormalyzerEvaluationResults(nr)
    ner(nr) <- ner
    
    nr
}
```

Kind regards,

Igy

**Comment by Jakob37** [comment]
Dear Igy, thanks for noticing us about this. Sorry about the slow response - I am currently on parental leave and only occasionally have time at the computer!

Yes, we should take a look.

Do you know more about this one @flevander ?

**Comment by Jakob37** [comment]
Sorry for the very slow response time on this one. I am looking into it now.
