### ISSUE TITLE
Error in analyzeNormalizations 

### ISSUE THREAD

**Issue by jangrasicOIST** [ComputationalProteomics/NormalyzerDE#32]
When I run the example in the vignette, I receive the following error:
I'm using R version 4.3.1

> normalyzer(jobName = "vignette_run", designPath = designFp, dataPath = dataFp, outputDir = outDir)
You are running version 1.18.0 of NormalyzerDE
[Step 1/5] Load data and verify input
Input data checked. All fields are valid.
Sample check: More than one sample group found
Sample replication check: All samples have replicates
RT annotation column found (5)
[Step 1/5] Input verified, job directory prepared at:C:\Users\JAN-GR~1\AppData\Local\Temp\RtmpuW6HUX/vignette_run
[Step 2/5] Performing normalizations
[Step 2/5] Done!
[Step 3/5] Generating evaluation measures...
Error in match.arg(statistics, c("mean", "sd", "se(mean)", "var", "CV",  : 
  'arg' should be one of “mean”, “sd”, “se(mean)”, “var”, “CV”, “IQR”, “quantiles”, “skewness”, “kurtosis”

> normResultsWithEval <- analyzeNormalizations(normResults)
Error in match.arg(statistics, c("mean", "sd", "se(mean)", "var", "CV",  : 
  'arg' should be one of “mean”, “sd”, “se(mean)”, “var”, “CV”, “IQR”, “quantiles”, “skewness”, “kurtosis”

**Comment by Jakob37** [comment]
Thank you for noticing us. Something must have changed in the other packages used by NormalyzerDE. We will look into it.

**Comment by froz9** [comment]
I got the same error message when I ran NormalyzerDE locally. I had to run it into the webpage.

**Comment by Jakob37** [comment]
Thank you for the notice @froz9 . This is no longer part of my work duties, but I haven't forgotten it. I'll try to find the time to fix this ASAP.

**Comment by Jakob37** [comment]
I have identified and fixed the error locally. It was a package used by NormalyzerDE which had changed its signature. I also found that some other packages are deprecated. I am working on cleaning this up.

**Comment by shumpeim** [comment]
Hello! I am also running into this same issue. Just writing so that I know when this is fixed. For now, is there a temporary fix that you recommend?

**Comment by Jakob37** [comment]
> Hello! I am also running into this same issue. Just writing so that I know when this is fixed. For now, is there a temporary fix that you recommend?

If you are able to, then you could run the web server for now. I think that still runs an unaffected version of the imported packages.

You can also check out the branch I am working in for a temporary fix jw/fixing-deprecation-issues, if comfortable with Git that is

I have resolved the issue itself in that branch, but encountered other issues with dependencies for building the vignette. This needs to be fixed to build to Bioconductor. 

Thank you all for noticing me that this issue is affecting you. I'll continue looking into this the days ahead.

**Comment by Jakob37** [comment]
Just a quick update here. I have pushed a limited bug-fix to the release branch, and a more extensive fix removing some dependencies to the devel branch (which will be rolled into the release branch in about a month).

I will leave the issue open until I can confirm that the Bioconductor checks have went through OK.

**Comment by Jakob37** [comment]
The develop branch get status "OK" now. So you should be able to run NormalyzerDE locally now if installing it through either the Bioconductor develop branch or by installing the `devel` branch directly from GitHub.

Still waiting to see if the patching of the release version went through OK.

**Comment by Jakob37** [comment]
Now the release branch also get status "OK" in the Bioconductor builds. I'll close the issue. Let us know if you still encounter any problems!

**Comment by aleighbrown** [comment]
I'm getting the same error actually on the vignette data

```
devtools::install_github("ComputationalProteomics/NormalyzerDE",ref = "devel")
normalyzer(jobName="sumExpRun", experimentObj = sumExpObj, outputDir=outDir)
You are running version 1.23.2 of NormalyzerDE
[Step 1/5] Load data and verify input
Input data checked. All fields are valid.
Sample check: More than one sample group found
Sample replication check: All samples have replicates
RT annotation column found (5)
[Step 1/5] Input verified, job directory prepared at:/var/folders/xr/lmkkh0p10t948k1n104z1jsh0000gn/T//RtmpvtdAkF/sumExpRun
[Step 2/5] Performing normalizations
[Step 2/5] Done!
[Step 3/5] Generating evaluation measures...
Error in match.arg(statistics, c("mean", "sd", "se(mean)", "var", "CV",  : 
  'arg' should be one of “mean”, “sd”, “se(mean)”, “var”, “CV”, “IQR”, “quantiles”, “skewness”, “kurtosis”
  ```

**Comment by aleighbrown** [comment]
Wait - nvm - just kidding - just needed to restart R after the re-install! Ignore!

**Comment by Jakob37** [comment]
Gave me a scare there :wink: Happy to hear it is working!
