### ISSUE TITLE
Is log2-transformed the output data?

### ISSUE THREAD

**Issue by froz9** [ComputationalProteomics/NormalyzerDE#35]
Hi, I'm working on a project that uses your output data and I have a question. How did you transform the data? Is it log2 or some other base? Thanks for your help.

**Comment by Jakob37** [comment]
Hi @froz9 ! Yes, by default the output-data is log2-transformed.

**Comment by Jakob37** [comment]
I'll close the issue, but feel free to follow up if you have more questions.

Good luck with the project!

**Comment by froz9** [comment]
Thank you for your prompt attention to the issue. I appreciate your help. Have a great day!
