### ISSUE TITLE
error in normalization

### ISSUE THREAD

**Issue by fionamassspec** [ComputationalProteomics/NormalyzerDE#36]
Dear Mr. Willforss,

I'm currently using your NormalyzerDE package for my proteomics data analysis. I was doing the analyze normalization step but got error when running it.

Error in vapply(methodList, calculateFeatureCVVector, rep(0, numberFeatures)) : 
  values must be length 4418,
 but FUN(X[[9]]) result is length 4419

It looks like the error caused by the data with too many rows (4500). Any solutions for this?

Thanks.

**Comment by Jakob37** [comment]
@fionamassspec Thank you for using NormalyzerDE!

Did the error remain? There might be rows with many missing values. If you still have the issue, let me know and I can help you with further debugging.
