### ISSUE TITLE
Warning with deprecrated feature in ggplot

### ISSUE THREAD

**Issue by Bizes** [ComputationalProteomics/NormalyzerDE#37]
When running normalzyerDE to compare the conditions it finishes the calculations but gives this warning.

As it seems to be working fine this is not urgent but should be an easy fix.

The `guide` argument in `scale_*()` cannot be `FALSE`. This was deprecated in ggplot2 3.3.4.
ℹ Please use "none" instead.
ℹ The deprecated feature was likely used in the NormalyzerDE package.
  Please report the issue to the authors.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.

**Comment by Jakob37** [comment]
Thank you for noticing us! I'll keep this in mind, and see if I can fix it next time I am poking around in the NormalyzerDE code.

**Comment by heuselm** [comment]
+1, got this warning, too
