### ISSUE TITLE
Exporting relevant intragroup variations functions

### ISSUE THREAD

**Issue by lisiarend** [ComputationalProteomics/NormalyzerDE#38]
Hey,

I wanted to ask if it is possible to export the functions `calculateSummarizedCorrelationVector`, `calculateReplicateCV`, `calculatePercentageAvgDiffInMat`, `calculateAvgMadMem`, `calculateAvgReplicateVariation` because I am currently developing a new package and would want to use them to calculate typical intragroup variation metrics such as PMAD, PEV, and PCV.

**Comment by Jakob37** [comment]
> Hey,
> 
> I wanted to ask if it is possible to export the functions `calculateSummarizedCorrelationVector`, `calculateReplicateCV`, `calculatePercentageAvgDiffInMat`, `calculateAvgMadMem`, `calculateAvgReplicateVariation` because I am currently developing a new package and would want to use them to calculate typical intragroup variation metrics such as PMAD, PEV, and PCV.

Hi @lisiarend ! Happy to hear that you are interested in using functionality from NormalyzerDE.

Yes, sure, I think it would be fine to export these as well. I'll look into exporting them the coming week!

**Comment by lisiarend** [comment]
Any news on this?

**Comment by Jakob37** [comment]
> Any news on this?

Hi! Thank you for the ping (and patience). I'll try to prioritize this the coming weeks.

**Comment by Jakob37** [comment]
Hi again. Sorry about the delay, NormalyzerDE is not part of my work anymore, but maintained in my freetime.

I have taken a closer look at the code, and realized that it unfortunately isn't structured such that these functions can be used independently. They are tightly linked to a NormalyzerDE class `NormalyzerEvaluationResults`. This one is exported and could potentially be used externally for calculating these measures. But I think you would be better off either:

1. Finding a package specialized in calculating statistical metrics (not sure which is the best one at the moment, but it should exist ..)
2. Take inspiration of the NormalyzerDE code, copy and update (and leave an acknowledgement :pray: ).

If it was better structured, these functions could have been free standing and accessible in the way you would like. I would have written it differently today, but it is outside my ability to rewrite this now.

Hope this is OK and that you find a solution. Feel free to follow up if you have any questions or thoughts!
