### ISSUE TITLE
Error converting 0's to NAs

### ISSUE THREAD

**Issue by arnscott** [ComputationalProteomics/NormalyzerDE#6]
If the 0 value in the file is shown as 0.0 (a floating point value) there is an error handling these values:

[Step 1/5] Input verified, job directory prepared at:./norm_place_holders
[Step 2/5] Performing normalizations
Error in qr.default(x) : NA/NaN/Inf in foreign function call (arg 1)

Changing the 0.0's to 0's fixed this (just using sed) but it might be nice to accept floating point 0.0's as well to be less restrictive!

**Comment by Jakob37** [comment]
Should be fixed now!
