### ISSUE TITLE
Input verification of MaxQuant input data fails

### ISSUE THREAD

**Issue by flevander** [ComputationalProteomics/NormalyzerDE#9]
When using and specifying any of the MaxQuant input data formats the validation of the design matrix fails as the headers in the MQ tables contain "Intensity " + the sample name which is not matching the sample names in the design file. The data thus need to pass the preparser function before validation of the design matrix sample names vs the data, which should solve the problem.

**Comment by Jakob37** [comment]
I believe this is solved now. At least a test-dataset I ran works successfully in the web interface (version 1.3.2). Please notice me if you still encounter this problem.
